# Import

```{r}
library(dplyr)
library(here)
devtools::load_all()
```

# Load data

```{r}
load(here("data", "NHANES3.rda"))
load(here("data", "NHANES4.rda"))
```

# Remove old bioage calculations

```{r}
NHANES3 <- NHANES3 %>%
  select(
    -kdm0,
    -kdm_advance0,
    -phenoage0,
    -phenoage_advance0
  )
NHANES4 <- NHANES4 %>%
  select(
    -kdm0,
    -kdm_advance0,
    -phenoage0,
    -phenoage_advance0
  )
```

# Recalculate KDM values

## KDM V1

```{r}
biomarkers <- c("fev", "sbp", "totchol", "hba1c", "albumin", "creat", "lncrp", "alp", "bun")

train_fem <- kdm_calc(
  data = NHANES3 %>%
    filter(
      gender == 2 & age >= 30 & age <= 75 & pregnant == 0,
      !(rowSums(is.na(across(all_of(biomarkers)))) > 2)
    ),
  biomarkers,
  fit = NULL,
  s_ba2 = NULL
)
train_male <- kdm_calc(
  data = NHANES3 %>%
    filter(
      gender == 1 & age >= 30 & age <= 75 & pregnant == 0,
      !(rowSums(is.na(across(all_of(biomarkers)))) > 2)
    ),
  biomarkers,
  fit = NULL,
  s_ba2 = NULL
)

test_fem <- kdm_calc(
  data = NHANES4 %>%
    filter(
      gender == 2,
      !(rowSums(is.na(across(all_of(biomarkers)))) > 2)
    ),
  biomarkers,
  fit = train_fem$fit,
  s_ba2 = train_fem$fit$s_ba2
)

test_male <- kdm_calc(
  data = NHANES4 %>%
    filter(
      gender == 1,
      !(rowSums(is.na(across(all_of(biomarkers)))) > 2)
    ),
  biomarkers,
  fit = train_male$fit,
  s_ba2 = train_male$fit$s_ba2
)

train <- rbind(train_fem$data, train_male$data) %>% rename(kdm0 = kdm, kdm_advance0 = kdm_advance)

test <- rbind(test_fem$data, test_male$data) %>% rename(kdm0 = kdm, kdm_advance0 = kdm_advance)

NHANES3 <- left_join(NHANES3, train[, c("sampleID", "kdm0", "kdm_advance0")], by = "sampleID")
NHANES4 <- left_join(NHANES4, test[, c("sampleID", "kdm0", "kdm_advance0")], by = "sampleID")
```

## KDM V2

```{r}
biomarkers <- c("albumin", "alp", "lncrp", "totchol", "lncreat", "hba1c", "sbp", "bun", "uap", "lymph", "mcv", "wbc")

train_fem <- kdm_calc(
  data = NHANES3 %>%
    filter(
      gender == 2 & age >= 30 & age <= 75 & pregnant == 0,
      !(rowSums(is.na(across(all_of(biomarkers)))) > 2)
    ),
  biomarkers,
  fit = NULL,
  s_ba2 = NULL
)
train_male <- kdm_calc(
  data = NHANES3 %>%
    filter(
      gender == 1 & age >= 30 & age <= 75 & pregnant == 0,
      !(rowSums(is.na(across(all_of(biomarkers)))) > 2)
    ),
  biomarkers,
  fit = NULL,
  s_ba2 = NULL
)

test_fem <- kdm_calc(
  data = NHANES4 %>% filter(
    gender == 2,
    !(rowSums(is.na(across(all_of(biomarkers)))) > 2)
  ),
  biomarkers,
  fit = train_fem$fit,
  s_ba2 = train_fem$fit$s_ba2
)

test_male <- kdm_calc(
  data = NHANES4 %>%
    filter(
      gender == 1,
      !(rowSums(is.na(across(all_of(biomarkers)))) > 2)
    ),
  biomarkers,
  fit = train_male$fit,
  s_ba2 = train_male$fit$s_ba2
)

train <- rbind(train_fem$data, train_male$data)

test <- rbind(test_fem$data, test_male$data)

NHANES3 <- left_join(NHANES3, train[, c("sampleID", "kdm", "kdm_advance")], by = "sampleID")
NHANES4 <- left_join(NHANES4, test[, c("sampleID", "kdm", "kdm_advance")], by = "sampleID")
```

# Plot

```{r}
#select biological age variables
agevar = c("kdm0","kdm")

#prepare labels
label = c("KDM V1\nBiological Age",
          "KDM V2\nBiological Age")

#plot age vs bioage
plot_ba(NHANES4, agevar, label)
```
